### ISSUE TITLE
%cal and %cls not parsed

### ISSUE THREAD

**Issue by ArneVogel** [kevinludwig/pgn-parser#8]
Hi,

nice library! Unfortunately %cal and %cls (arrows and square highlighting on the chess board) information is currently not parsed and creates an error.  

Example (from https://lichess.org/study/D6DfYHZe):

```
{ [%csl Gf3,Gc6][%cal Gd2d4] }
1. e4 { this is a comment } { [%csl Gd5,Gf5][%cal Ge4d5,Ge4f5] } *
```

Also could you add a license to the project so others (like me :) ) could use it?

**Comment by kevinludwig** [comment]
Hi, I'll take a look, thanks. When I fix I'll throw in a MIT license.

**Comment by kevinludwig** [comment]
OK so the thing that is not parsing in your example above, is not the command per-se, but that I've allowed for only a single comment per half move. I.e. by my parser rules (which are probably too strict), I allow something like this:

```
1. e4 {one comment allowed} e5 {and one here} 2. d4 {and this is OK}
```

Which produces a parsed result of:

```
[
  {
    "comment_above_header": null,
    "headers": {},
    "comment": null,
    "moves": [
      {
        "move_number": 1,
        "move": "e4",
        "comment": "one comment allowed"
      },
      {
        "move": "e5",
        "comment": "and one here"
      },
      {
        "move_number": 2,
        "move": "d4",
        "comment": "and this is OK"
      }
    ],
    "result": "*"
  }
]
```

If I change to this, it breaks:

```
1. e4 {one comment allowed} e5 {and one here} 2. d4 {and this is OK} {but this breaks!}
```

So, minimally, I can change the output schema to be like this:

```
[
  {
    "comment_above_header": null,
    "headers": {},
    "comment": null,
    "moves": [
      {
        "move_number": 1,
        "move": "e4",
        "comments": ["one comment allowed"]
      },
      {
        "move": "e5",
        "comments": ["and one here"]
      },
      {
        "move_number": 2,
        "move": "d4",
        "comments": ["and this is OK", "but this breaks!"]
      }
    ],
    "result": "*"
  }
]
```

I.e. change the object key from "comment" to comments" and make it an array of comments. Going back to your original example, you'd get this:

```
[
  {
    "comment_above_header": [
      " [%csl Gf3,Gc6][%cal Gd2d4] "
    ],
    "headers": {},
    "comment": null,
    "moves": [
      {
        "move_number": 1,
        "move": "e4",
        "comments": ["this is a comment", " [%csl Gd5,Gf5][%cal Ge4d5,Ge4f5] "]
      }
    ],
    "result": "*"
  }
]
```

To be honest, I'd probably change all array keys (like top level "comment_above_header" and "comment") to be plural. 

And since I'm breaking the API contract I'd probably also convert the headers from object key/value to array. Something I noticed the other day was that by throwing the headers in Object I'm losing the original order specified in the PGN, which I'd rather keep. 

I'm not sure if this is what you were looking for--just getting a clean parse--or if you were hoping that the embedded commands would get parsed out. Like if I was going to get super fancy I might do (using your example above:

```
[
  {
    "comments_above_header": [
      { commands: [{name: "csl", value: "Gf3,Gc6"}, {name: "cal", value: "Gd2d4"}] }
    ],
    "headers": [],
    "comments": null,
    "moves": [
      {
        "move_number": 1,
        "move": "e4",
        "comments": [{text: "this is a comment"}, { commands: [{name: "csl", value: "Gd5,Gf5"}, {name: "cal", value: "Ge4d5,Ge4f5"}] }]
      }
    ],
    "result": "*"
  }
]
```

**Comment by kevinludwig** [comment]
Here's the minimal change (where it just parses multiple comments between half move),

https://github.com/kevinludwig/pgn-parser/pull/9

I may merge this and publish as v2.0.0 since this is a trivial change that gets the file parsed and I need to think a bit more about how to get the commands parsed out of the middle of comments (which generally seems like a nice feature, since I imagine a PGN viewer that knows what to do with commands would want to distinguish between regular commentary and commands, and a PGN viewer that doesn't handle commands might like to ignore them entirely.

**Comment by kevinludwig** [comment]
Also just threw in one last change--I made the comment schema be like 

```
comments: [ 
    {
        text: "some comment text here"
    }
]
```

Which just means that later on if I decide to parse out the command text I won't have to make breaking changes to the schema to do so.

**Comment by ArneVogel** [comment]
If I could choose I would probably prefer the super fancy version with the commands being parsed. Saved consumers of the library on all implement it independently. I think its a widely enough used (lichess, chessbase, chesscafe) to support it, if its possible.

**Comment by kevinludwig** [comment]
OK, so this is what I have working, let me know if this works. This is your parsed example:

```
[
  {
    "comments_above_header": [
      {
        "commands": [
          {
            "key": "csl",
            "values": [
              "Gf3",
              "Gc6"
            ]
          },
          {
            "key": "cal",
            "values": [
              "Gd2d4"
            ]
          }
        ]
      }
    ],
    "headers": null,
    "comments": null,
    "moves": [
      {
        "move_number": 1,
        "move": "e4",
        "comments": [
          {
            "text": " this is a comment "
          },
          {
            "commands": [
              {
                "key": "csl",
                "values": [
                  "Gd5",
                  "Gf5"
                ]
              },
              {
                "key": "cal",
                "values": [
                  "Ge4d5",
                  "Ge4f5"
                ]
              }
            ]
          }
        ]
      }
    ],
    "result": "*"
  }
]
```

I am not 100% spec compliant. Right now, a comment is either a list of commands, or a plain text comment (which works for your example, and I imagine for most real world cases. The spec actually says that a comment can have optional lead free text, followed by a command, followed by an optional trailing free text comment. I think if you're OK with this, I'll release as is with that known issue.

**Comment by ArneVogel** [comment]
Looks awesome. Playing around with the grammar on https://pegjs.org/online I found a small bug left, with this pgn:

```
[Event "Arrows: Chapter 1"]
[Site "https://lichess.org/study/gtwXN98j/BUpcKybi"]
[Result "*"]
[UTCDate "2019.04.15"]
[UTCTime "17:12:39"]
[Variant "Standard"]
[ECO "A00"]
[Opening "Mieses Opening"]
[Annotator "https://lichess.org/@/ArneVogel"]

{ initial position } { [%csl Gb8,Gb1][%cal Ga1a8] }
1. d3 { first move } { [%csl Ga5,Gh5][%cal Ga3h3,Gh4a4] } *
```
I am getting this error:
```
Line 11, column 22: Expected " ", "*", ".", "0-1", "1-0", "1/2-1/2", "O-O", "O-O-O", "\n", "\r", "\t", "\x0C", [1-9], [NKQRB], or [a-h] but "{" found.
```
Curiously without the headers its getting parsed correctly.

**Comment by kevinludwig** [comment]
weird. yeah let me fix that and then I'm going to push it out as 2.0.0. It's the whitespace between the two lead comments. If you remove the headers it parses them has comments_above_header. So I must be missing something that eats extra space at that one place.

**Comment by kevinludwig** [comment]
Fixed and published. Its up as 2.0.0. Thanks and let me know if you run across anything else.
